name: Build thesis

# Controls when the action will run.
on:
  # Triggers the workflow on push but only for the main branch
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: thesis/
    # Steps represent a sequence of tasks that will be executed as part of the
    # job
    steps:
      - uses: actions/checkout@v3
      - uses: reitermarkus/latexmk@main
      - run: mkdir pages && mv thesis/*.pdf pages/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: pages/
