name: Build thesis

# Controls when the action will run.
on:
  # Triggers the workflow on push but only for the main branch
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the
    # job
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: actions/cache@v3
        name: Tectonic Cache
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-
      - uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          biber-version: "latest"
      - name: Run Tectonic + Biber
        run: cd thesis/ && tectonic thesis.tex && cd ..
      - name: Prepare pages folder
        run: mkdir pages/ && mv thesis/*.pdf pages/
      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          path: pages/
